# Generated by Django 5.1.6 on 2025-03-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_options_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('To Do', 'TODO'), ('In Progress', 'IN_PROGRESS'), ('Completed', 'COMPLETED')], default='TODO', max_length=20),
        ),
    ]
